// Code generated by gandalf(BuildDate: 2021-06-02 17:41:53, Version: d1ca83d (2021-06-01 19:18:22 +0530)). DO NOT EDIT.
package main

import (
	"encoding/binary"
)

func (s *TestBin) Marshal() []byte {
	ln := 0
	ln += len(s.Name)
	ln += len(s.NameBytes)
	ln += 4
	ln += 8
	dest := make([]byte, ln)
	offset := 0
	copy(dest[offset:offset+len(s.Name)], []byte(s.Name))
	offset += len(s.Name)
	copy(dest[offset:offset+len(s.NameBytes)], []byte(s.NameBytes))
	offset += len(s.NameBytes)
	binary.BigEndian.PutUint32(dest[offset:offset+4], uint32(s.Age))
	offset += 4
	binary.BigEndian.PutUint64(dest[offset:offset+8], uint64(s.Age2))
	offset += 8
	return dest
}
