env:
  - CGO_ENABLED=0
builds:
  - binary: binserde
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    dir: cmd/generator
    ldflags:
      - -s -w -X "main.buildVersion={{ .Tag }} ({{ .ShortCommit }} {{ .Date }})"
    hooks:
      # stuff executables with static assets.
      post: make pack-releases

archives:
  - format: tar.gz
    files:
      - README.md
      - LICENSE
